engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: true
    config:
      languages:
        javascript:
ratings:
  paths:
    - lib/**
    - "**.js"
exclude_paths:
  - "specs/"
  - "dist/"
  - "examples/"
